ai:
    platform:
        ollama:
            endpoint: '%env(OLLAMA_ENDPOINT)%'

    agent:
        default:
            platform: ai.platform.ollama
            model: balanced-qwen3.6

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
