services:
  web:
    image: ${IMAGES_PREFIX:-the-doomsday-machine:}web${IMAGES_POSTFIX:--dev-latest}

    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

    volumes:
      - ./:/app
      - ./docker/containers/web/rootfs/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./docker/containers/web/rootfs/usr/local/etc/php/app.conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro

    command: ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch"]

    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  cli:
    image: ${IMAGES_PREFIX:-the-doomsday-machine:}cli${IMAGES_POSTFIX:--dev-latest}

    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

    volumes:
      - ./:/app

    command: ['sleep', 'infinity'] # TODO: wait for db...
