#!/bin/bash

set -e

PGPASSWORD="${POSTGRES_PASSWORD:-admin}" psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER:-admin}" --dbname "${POSTGRES_DB:-app}" <<-EOSQL
	CREATE USER ${POSTGRES_READER_USER:-reader} WITH PASSWORD '${POSTGRES_READER_PASSWORD:-reader}';
	CREATE USER ${POSTGRES_WRITER_USER:-writer} WITH PASSWORD '${POSTGRES_WRITER_PASSWORD:-writer}';
	CREATE USER ${POSTGRES_MIGRATOR_USER:-migrator} WITH CREATEDB CREATEROLE PASSWORD '${POSTGRES_MIGRATOR_PASSWORD:-migrator}';

	ALTER DATABASE "${POSTGRES_DB:-app}" OWNER TO ${POSTGRES_MIGRATOR_USER:-migrator};
EOSQL

PGPASSWORD="${POSTGRES_MIGRATOR_PASSWORD:-migrator}" psql -v ON_ERROR_STOP=1 --username "${POSTGRES_MIGRATOR_USER:-migrator}" --dbname "${POSTGRES_DB:-app}" <<-EOSQL
	-- ${POSTGRES_READER_USER:-reader}
	-- SEQUENCE
	GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_READER_USER:-reader}; -- Grant access to existing sequences in public schema
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO ${POSTGRES_READER_USER:-reader}; -- Grant access to future sequences in public schema
	-- TABLE (and table-like objects)
	GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READER_USER:-reader}; -- Grant access to existing tables in public schema
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_READER_USER:-reader}; -- Grant access to future tables in public schema

	-- ${POSTGRES_WRITER_USER:-writer}
	-- SEQUENCE
	GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_WRITER_USER:-writer};
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_WRITER_USER:-writer};
	-- TABLE (and table-like objects)
	GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_WRITER_USER:-writer};
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_WRITER_USER:-writer};

	-- ${POSTGRES_MIGRATOR_USER:-migrator}
	-- SEQUENCE
	GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MIGRATOR_USER:-migrator};
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${POSTGRES_MIGRATOR_USER:-migrator};
	-- TABLE (and table-like objects)
	GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MIGRATOR_USER:-migrator};
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ${POSTGRES_MIGRATOR_USER:-migrator};
EOSQL
