name: Trunk

on:
  push:
    branches:
      - main

    pull_request: ~

    workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

  cancel-in-progress: true

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            docker/bake.hcl
            docker/env.hcl
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start Services
        run: docker compose up --wait --no-build || (docker compose logs && exit 1)

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Builder Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/builder/Dockerfile
          
      - name: Lint CLI Base Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/cli/base.Dockerfile

      - name: Lint CLI Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/cli/Dockerfile

      - name: Lint Web Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/web/Dockerfile
