name: Trunk

on:
  push:
    branches:
      - main

  pull_request: ~

  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

  cancel-in-progress: true

jobs:
  ci:
    name: CI

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Images
        uses: docker/bake-action@v4
        with:
          pull: true
          load: true
          files: |
            docker/bake.hcl
            docker/env.ci.hcl
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max

      - name: Start Services
        run: docker compose -f compose.yaml -f compose.ci.yaml up --wait --no-build || (docker compose logs && exit 1)
        
      - name: Create Test Database
        run: docker compose exec -T cli bin/console -e test doctrine:database:create --connection migrator

      - name: Run Migrations
        run: docker compose exec -T cli bin/console -e test doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit
        run: docker compose exec -T -e APP_ENV=test -e XDEBUG_MODE=coverage cli bin/phpunit --coverage-text --coverage-clover clover.xml --coverage-html coverage 

      - name: Copy Coverage To Host
        run: docker cp the-doomsday-machine-cli-1:/app/coverage/ ./coverage && docker cp the-doomsday-machine-cli-1:/app/clover.xml .

      - name: Make Coverage Badge
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        if: github.ref == 'refs/heads/main'
        with:
          coverage_badge_path: coverage/coverage.svg
          push_badge: false

      - name: Persist Coverage
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          publish_dir: ./coverage 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'doom-bot'
          user_email: 'doom-bot@users.noreply.github.com'

  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Builder Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/builder/Dockerfile
          ignore: DL3006

      - name: Lint CLI Base Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/cli/base.Dockerfile
          ignore: DL3006

      - name: Lint CLI Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/cli/Dockerfile
          ignore: DL3006

      - name: Lint Web Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/containers/web/Dockerfile
          ignore: DL3006
